In [1]:
import numpy as np
import pandas as pd

In [3]:
df1=pd.read_csv('sucides_over_world.csv')
df2=pd.read_csv('sucides_in_india.csv')

In [4]:
df1.head()

   country  year     sex          age  suicides_no  population
0  Albania  1985  female  15-24 years          NaN    277900.0
1  Albania  1985  female  25-34 years          NaN    246800.0
2  Albania  1985  female  35-54 years          NaN    267500.0
3  Albania  1985  female   5-14 years          NaN    298300.0
4  Albania  1985  female  55-74 years          NaN    138700.0

In [7]:
df2.head()

,Gender,Age_Bracket,Cause,Sub-Cause,Number_of_cases
0,Female 29.07%,18 to 29 40.62%,Bankruptcy or Indebtedness,NaN,135
1,Female 29.07%,18 to 29 40.62%,Causes Not Known,NaN,1873
2,Female 29.07%,18 to 29 40.62%,Death of Dear Person,NaN,178
3,Female 29.07%,18 to 29 40.62%,Drug Abuse/Alcoholic Addiction,NaN,38
4,Female 29.07%,18 to 29 40.62%,Failure in Examination,NaN,340